import { expect, test } from '@playwright/test'

const scaleName = 'Basculer entre le centre et la région'
test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.paris-status')).toContainText('977 missions planifiées')
})

test('the heart retains playback and regional branches while adding and inspecting the arcs', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  const clock = page.getByRole('slider', { name: 'Heure' })
  const before = Number(await clock.inputValue())
  await page.getByRole('button', { name: scaleName }).click()
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '1.000')
  await expect(page.locator('main')).toHaveAttribute('data-layout-transitioning', 'false')
  await expect.poll(async () => Number(await clock.inputValue())).toBeGreaterThan(before)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const paused = await clock.inputValue()
  await page.getByRole('button', { name: 'Révéler les arcs · Métro 2 et 6' }).click()
  await expect(page.locator('.paris-status')).toContainText('1225 missions planifiées')
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '1.000')
  await expect(clock).toHaveValue(paused)
  await page.waitForTimeout(1800)
  await page.screenshot({ path: testInfo.outputPath('heart-arcs.png') })
  const search = page.getByRole('searchbox')
  await search.fill('Métro 2')
  await page.getByRole('option', { name: /^Métro 2 \d+ MISSIONS PLANIFIÉES$/ }).click()
  await expect(page.locator('main')).toHaveAttribute('data-scale-view', 'centre')
  await expect(page.locator('.paris-status')).toContainText('Métro 2')
  await search.fill('Cergy le Haut')
  await page.getByRole('option', { name: 'Cergy le Haut STATION', exact: true }).click()
  await expect(page.locator('.paris-status')).toContainText('Cergy le Haut')
  await expect(page.locator('main')).toHaveAttribute('data-scale-view', 'centre')
  await page.getByRole('button', { name: 'Réinitialiser la carte' }).click()
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '0.000')
  await expect(page.locator('.paris-status')).toContainText('1225 missions planifiées')
  await expect(clock).toHaveValue(paused)
  expect(errors).toEqual([])
})

test('rapid reversal and reduced motion settle in the requested composition', async ({ page }) => {
  const scale = page.getByRole('button', { name: scaleName })
  await scale.click()
  await expect.poll(async () => Number(await page.locator('main').getAttribute('data-layout-mix'))).toBeGreaterThan(0)
  await scale.click()
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '0.000')
  await expect(page.locator('main')).toHaveAttribute('data-layout-transitioning', 'false')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await scale.click()
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '1.000')
  await expect(page.locator('main')).toHaveAttribute('data-layout-transitioning', 'false')
  await page.getByRole('button', { name: 'Réinitialiser la carte' }).click()
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '0.000')
})

test('failed arcs can be retried in the heart and keep the full-day clock', async ({ page }) => {
  let failed = false
  await page.route('**/correspondances-metro-arcs-morning.json', async (route) => {
    if (!failed) { failed = true; await route.fulfill({ status: 503, body: 'Unavailable' }) }
    else await route.continue()
  })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: scaleName }).click()
  await page.getByRole('button', { name: 'Révéler les arcs · Métro 2 et 6' }).click()
  await page.getByRole('button', { name: 'Réessayer les arcs · 2 et 6' }).click()
  await expect(page.locator('.paris-status')).toContainText('1225 missions planifiées')
  await page.getByRole('button', { name: 'Étude de vingt-quatre heures' }).click()
  await expect(page.locator('.paris-status')).toContainText('6478 missions planifiées')
  const clock = page.getByRole('slider', { name: 'Heure' })
  await clock.fill('43200')
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '1.000')
  await expect(page.locator('.paris-heart-note')).toContainText('Métro 2 au nord')
  await expect(page.locator('.paris-status')).not.toContainText('se chargent')
  await expect(clock).toHaveValue('43200')
})

test('AIR isolation returns to geography while keeping its enabled state', async ({ page }) => {
  await page.getByRole('button', { name: 'AIR — avions observés' }).click()
  await expect(page.locator('.paris-air-note')).toContainText('avions observés')
  await page.getByRole('button', { name: scaleName }).click()
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '1.000')
  await expect(page.locator('.paris-air-note')).toContainText('visible en Région')
  await page.getByRole('button', { name: 'Afficher les couches' }).click()
  await page.getByRole('button', { name: 'Isoler les avions observés' }).click()
  await expect(page.locator('main')).toHaveAttribute('data-scale-view', 'region')
  await expect(page.locator('main')).toHaveAttribute('data-layout-mix', '0.000')
  await expect(page.locator('main')).toHaveAttribute('data-air-enabled', 'true')
  await expect(page.locator('.paris-status')).toContainText('Le ciel parisien')
})
