/// <reference lib="dom" />
import { expect, test } from '@playwright/test'
test('station departures fit narrow cards and select their study train', async ({ page }) => {
 await page.emulateMedia({ reducedMotion: 'reduce' })
 await page.goto('/')
 await expect(page.locator('canvas').first()).toBeVisible()
 expect(await page.evaluate(() => performance.getEntriesByType('resource').some(entry => entry.name.includes('VehicleJourneyCard')))).toBe(false)
 expect(await page.evaluate(() => performance.getEntriesByType('resource').some(entry => entry.name.includes('StationDeparturesCard')))).toBe(false)
 const stationResponse = page.waitForResponse(response => response.url().includes('StationDeparturesCard'))
 const search = page.getByRole('searchbox')
 await search.fill('chatelet')
 await page.getByRole('option').first().click()
 expect((await stationResponse).ok()).toBe(true)
 const card = page.locator('.edition-station-hero')
 await expect(card.locator('.ms-dot-matrix-board')).toBeVisible()
 await expect(card.locator('tbody button').first()).toBeVisible()
 for (const width of [280, 360, 520]) {
   await card.evaluate((element, width) => { (element as HTMLElement).style.width = `${Math.min(width, innerWidth - 72)}px` }, width)
   await expect.poll(() => card.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
 }
 await page.screenshot({ path: 'test-results/station-hero.png' })
 const vehicleResponse = page.waitForResponse(response => response.url().includes('VehicleJourneyCard'))
 await card.locator('tbody button').first().click()
 expect((await vehicleResponse).ok()).toBe(true)
 await expect(card).toHaveCount(0)
  const vehicle = page.locator('.ms-vehicle-hero')
  await expect(vehicle).toBeVisible()
  await expect(vehicle.locator('.ms-vehicle-hero__next')).toBeVisible()
  expect(await vehicle.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.locator('.edition-vehicle-hero').screenshot({ path: 'test-results/vehicle-hero.png' })
})
